### PR TITLE
Merge/upstream changes

### PR DESCRIPTION
**Pull request by mengtzu**
Picking up the upstream changes in seek-style-guide.

We'll want to do this regularly; even while we'll be adding a large amount of branded content, we want to keep as close to the parent repo as possible so we can share features.

### CODE REVIEW

**Comment by ZhenYongSeekAsia** [comment]
so many changes, @mengtzu do we have any efficient way to review this kind of changes.

**Comment by grillp** [comment]
@ZhenYongSeekAsia, by being more vigilant with respect to pulling changes back from the upstream master, we can avoid these mega-merges in the future.

**Comment by mengtzu** [comment]
@ZhenYongSeekAsia if it helps I approved most of those changes myself :)  The only easy way to do it is stay on top of developments in the seek-style-guide channel and merge in often.

**Comment by nicolassenechal** [comment]
How do we ensure that those changes won't impact any of our (future) front-ends? Do we need to start thinking of functional testing and screenshot testing now?

**Comment by mengtzu** [comment]
@nicolassenechal Yeah, we need to worry about that regardless if it's an upstream change from `seek-style-guide` or a direct change to `seek-asia-style-guide`.

The likely workflow would be change to `seek-asia-style-guide` (passing its internal tests) --> PR to `srp-react` picking up the new npm package (which must pass manual/functional/screenshot tests)

**Comment by mengtzu** [comment]
I'd like to merge this, and hopefully make it the last megamerge.  Can I get an approval? :)

**Pull request merged**
