### PR TITLE
fix(ImageSlider): remove unuse component

### PR DESCRIPTION
**Pull request by youwei91**
This PR is remove the unuse component in `ImageSlider` due to there is a better way to handle it without update style-guide.

Refer to this card & PR:
- https://trello.com/c/OvzMn5os/113-omniture-analytics-homepage-feature-tracking-for-featured-companies
- https://github.com/seekinternational/srp-react/pull/595

Base on this PR change(https://github.com/seekinternational/srp-react/pull/618), the omniture tracking for feature companies no longer require update style-guide.

Currently I just alter my change before, not sure this component still use by other place else maybe we can remove it?

### CODE REVIEW

**Comment by mengtzu** [comment]
@hscgavin what's the status of this component?

**Comment by youwei91** [comment]
@mengtzu yeah, @hscgavin PR is replace this component entirely, so this PR was plan to remove the work I done before because now `srp-react` is no longer depends on this component anymore. So @mengtzu , what you suggest is leave the `LinkComponent` here for better handling in future use?

**Comment by mengtzu** [comment]
@youwei91 yes, if this component remains, it should have a `LinkRenderer`.  But it seems likely we should remove it, or replace it with Gavin's implementation.

**Comment by youwei91** [comment]
Yeah, `srp-react` didn't use this component anymore, so is it save to remove? I can make the change of PR into remove the component

**Comment by mengtzu** [comment]
@patrickliu-sa ☝️ what do you think?  If nobody else is using this component we can probably safely deprecate it.  It'd be a breaking change but if it doesn't represent the vision for an image slider it'd be for the best.

**Pull request merged**
