### PR TITLE
feat(jobCard): Highlight keyword on job title

### PR DESCRIPTION
**Pull request by hscgavin**
Highlight keyword / keywords on the job title

image

### CODE REVIEW

**Comment by hscgavin** [comment]
@nicolassenechal snapshot added.

**Comment by ZhenYongSeekAsia** [comment]
based on https://seekinternational.github.io/seek-asia-style-guide/typography, yelling + regular seem like similar to yelling alone.
How about use strong props for highlighted text, so we no need the highlight class to bold it? e.g.:
highlight text: yelling + strong
normal text: yelling.

**Comment by hscgavin** [comment]
@ZhenYongSeekAsia  `yelling` bolds the title on mobile. `regular` is used to override the css from yelling. What do think? I think we can change highlight to strong

**Comment by ZhenYongSeekAsia** [comment]
@hscgavin i see, sorry that i dint realize the yelling was bold in mobile, cause im looking from desktop view .

**Pull request merged**
