### PR TITLE
Fix/header responsive fit tablet

### PR DESCRIPTION
**Pull request by chiwongseekasia**
Update header to fit tablet width

1.) under 1024 ( mobile & portrait tablet), use mobile header
2.) 1024 or over  ( landscape tablet & desktop), use desktop header

image

image

https://trello.com/c/173f6IIM/142-bug-responsive-nav-issues-at-770px

### CODE REVIEW

**Comment by mengtzu** [comment]
I think `@new-desktop` is kind of weird, `new` doesn't tend to be a good name since it doesn't stay that way long :)  It also helps the legacy one stick around for a long time since the new status needs to be explicitly opted in to.

Do we want to just bite the bullet and release a breaking change with `@desktop` etc ported to the new values and expose a `@legacy-desktop`, `@legacy-mobile` etc for anyone who wants to keep the old values (which is probably no-one?  Maybe it's just `@anz-mobile` 😂 )

@patrickliu-sa ☝️

**Comment by patrickliu-sa** [comment]
> Do we want to just bite the bullet and release a breaking change with `@desktop` etc ported to the new values and expose a `@legacy-desktop`, `@legacy-mobile` etc for anyone who wants to keep the old values (which is probably no-one? Maybe it's just `@anz-mobile` 😂 )
> 
> @patrickliu-sa ☝️

We definitely need another PR to rename those variable name, but t-shirt size of such task might be huge

**Comment by patrickliu-sa** [comment]
@PepeFranco But are we going to show split view on mobile device no matter for portrait / landscape?

**Comment by chiwongseekasia** [comment]
@PepeFranco hows going on this one?

**Comment by chiwongseekasia** [comment]
yes, it's fixed, then I close my PR

**Pull request closed without merging**
