### PR TITLE
fix(JobCard):keep three selling point in branded split view

### PR DESCRIPTION
**Pull request by ChanJit**
** Please provide as much detail as possible, but feel free to remove irrelevant sections **

Bug fix the three selling points, currently branded Ad's three selling points were hidden during split view. The correct behaviour for branded ad should remain the three selling points even it is in a split view. For more information you can checkout following [trello card](https://trello.com/c/Jj42MJJo/708-brandedad-include-3-bullet-points-in-split-view-job-card)

BREAKING CHANGE:

none

RFC URL:

none

MIGRATION GUIDE:

Before:

none

After:

none

EXAMPLE USAGE:

none

SNAP SHOT:

split view three selling points

### CODE REVIEW

**Comment by kosanna** [comment]
Why do we need to differentiate with this approach for branded ads? Imo they should follow the same rules. Also that would be lovely if we entirely move out this logic outside of the styleguide, because this is a business concern, whereas style guide is a pure representation. So the jobCard component should ideally be only concerned about showSellingPoints prop passed to it

**Comment by ChanJit** [comment]
> Why do we need to differentiate with this approach for branded ads? Imo they should follow the same rules. Also that would be lovely if we entirely move out this logic outside of the styleguide, because this is a business concern, whereas style guide is a pure representation. So the jobCard component should ideally be only concerned about showSellingPoints prop passed to it

I think they do pay more for the branded ad so we do need to make it distinguish than the others, for detail you may ask may or ming about the design. Speaking about logic, I would suggest that move the entire `Job Card` out of style guide 😂 cause too many customize things going on the job card. It not just this `branded ad`. So i will suggest separate those business logic to another card.

**Comment by kosanna** [comment]
That never gets done when it's separated, so I normally prefer to sneak in a bit of improvements if we're touching anything related. JobCard will most likely be in the shared ui in the future, it means we should try detaching business logic from the component display logic whiles keeping it still separate from srp react, hence was the suggestion. It get's really muddy with all those conditions inside.

**Comment by kosanna** [comment]
cc @ChanJit

**Pull request merged**
