### PR TITLE
feat(ShowMore): Add in classname prop

### PR DESCRIPTION
**Pull request by hklo**
Add in className prop to create flexibility on customize the show more component

### CODE REVIEW

**Comment by mengtzu** [comment]
Since it's a prop, you'll want a test that shows it gets passed through.

(Also while I don't really mind the prop since it's vaguely a standard in the style guides, is there a use case here that the component itself should take care of?)

**Comment by hklo** [comment]
For bricks team, we have some special use case that a little bit different style on the show more component, and I not sure if it is general enough that show more component should handle itself. 
1. Read more / read less on the left
2. Background is transparent
3. No linear gradient

image

**Comment by kosanna** [comment]
I'd say here's a classic situation where you have to either a) accept global design of the component, b) raise it and change it. Diff you're looking for is really not major. So might be a good idea to collaborate and just come up with some middle-ground that would be acceptable for everyone, rather than doing minor tweaks on your end solely

**Comment by hklo** [comment]
Ok. noted.
I will create another PR for the ShowMore component changes.

**Pull request closed without merging**
