### PR TITLE
feat(grid-js): Add grid variables as JS

### PR DESCRIPTION
**Pull request by syakiruzair**
** Please provide as much detail as possible, but feel free to remove irrelevant sections **

The new salary range component for SRP requires the grid variables to be accessible in the component as the library being used is yet to allow className to be passed. Reference: https://github.com/seekinternational/srp-react/pull/309

BREAKING CHANGE:

RFC URL:

MIGRATION GUIDE:

EXAMPLE USAGE:

```js
import grid from 'seek-asia-style-guide/theme/layout/grid'
```

### CODE REVIEW

**Comment by patrickliu-sa** [comment]
Can we use CSS variable in CSS-in-JS environment? I'm wonder if we can have one variable say `:root {
--gridBase: 4px;}` for global scope and override it in component level.

**Comment by syakiruzair** [comment]
@patrickliu-sa The hard part is to access the variables in JS files. Maybe I can try something like this https://github.com/michaeltaranto/less-vars-to-js which might be able to remove the need to copy the values as raised by @mengtzu

**Comment by patrickliu-sa** [comment]
@syakiruzair Actually you can get and set css variables with native javascript method ;)
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by syakiruzair** [comment]
@patrickliu-sa I saw that earlier but can we use that for less as well?

**Comment by syakiruzair** [comment]
I realised that there are already implementations using `less-vars-to-js` in this style guide. So I am just following the approach.

**Comment by patrickliu-sa** [comment]
If we use less-vars-to-js in the past, can keep using that. We can explore more possibility of using CSS variable in the future.

**Comment by mengtzu** [comment]
@syakiruzair this is good to merge whenever

**Comment by syakiruzair** [comment]
Now then @mengtzu. Thanks :)

**Pull request merged**
