### PR TITLE
feat(Button): add isSelected state and style for button component

### PR DESCRIPTION
**Pull request by kenttan0214**
Add isSeleted state for button component which will having the selected style (darken backrgroud color)

### CODE REVIEW

**Comment by kenttan0214** [comment]
http://seek-asia-style-guide--a9acefc95f09c1ca09b8b9bcc7f41afa67968998.surge.sh/button

**Comment by ChanJit** [comment]
capture

may be just pick one ? `Active` and `isActive`?

**Comment by kenttan0214** [comment]
@ChanJit I am trying not to use back the existing active state as it actually have different behavior between active and isActive.

isActive will change the background color hence if combine this two will impact to existing component.

**Comment by kenttan0214** [comment]
since hover and active options are not control by props i will remove them from the demo options, hope this will reduce the confuse.

**Comment by mengtzu** [comment]
The point of those options is so you can see the button's behaviour though, I'm not sure if it's helpful to remove them.

More to the point, if the term is easily confused with an existing term, that's a pretty strong signal we need to change it.

Which designer were you working with on this one?

**Comment by kenttan0214** [comment]
@mengtzu I am working with Shazwan on this. For active and hover are not control by the prop I am thinking it might be not useful to show as on option? Or we can just rename isActive to something else.

**Comment by mengtzu** [comment]
Taking the discussion to that Trello card - I think it'll be simple to work out though

**Comment by patrickliu-sa** [comment]
Hover state option is useful as it works quite similar to the feature that Chrome dev tools provided
image

Is there a way to get this work for demo page only? That distinct hover props seems not necessary when it's being used in real world scenario...

**Comment by mengtzu** [comment]
@patrickliu-sa it is demo-only - note those options on the demo compose a class onto the component rather than setting a prop

**Comment by kenttan0214** [comment]
After discuss with @shawn-dsz we decided to name the state as isSelected. I have put back the active & hover demo options.

**Pull request merged**
