### PR TITLE
fix(icon): set classname scope to parent node

### PR DESCRIPTION
**Pull request by patrickliu-sa**
Found the custom class style only set to wrapped SVG only.  This PR should fix the problem by scoping style to the icon component root node instead.

iconclass

EXAMPLE USAGE:

```js
<Icon className={styles.customizeIconStyle} type="purchaseCredits" />
```

### CODE REVIEW

**Comment by mengtzu** [comment]
I remember there being a pattern of `svgClassName` and `className` to address the particular entities - do we need either or both?

**Comment by patrickliu-sa** [comment]
It seems `svgClassName` target CSS namespace (as it allows hyphenated class name), while `className` targets CSS-in-JS namespace (use camelCase naming).  I can't say we should make only one survive and kill another one.... 😅

I think this PR hoisted `svgClassName` to the level of component root node, make it equivalent to component root's `className`

**Comment by mengtzu** [comment]
Cool, looks good - any current usages that were depending on the old functionality?  If not seems like a legit fix.

**Comment by patrickliu-sa** [comment]
> Cool, looks good - any current usages that were depending on the old functionality? If not seems like a legit fix.

We set loose baseline style on SVG in `<Icon>` component, so it can be customized with some generic class name.

`svgClassName` works as explicit class for just the vector graphic part in other components, so I think we can still keep the old one in `code.js` for broader use.

**Pull request merged**
