### PR TITLE
feat(typography): migrate to SEEK Asia type system

### PR DESCRIPTION
**Pull request by mengtzu**
This PR implements SEEK Asia's typography system in place of SEEK Australia's.  

BREAKING CHANGE:

All `Text` props referring to type size (eg `heading`, `hero`) are deprecated, new prop names reflecting SEEK Asia type terminology have been added.

REASON FOR CHANGE:

SEEK Australia's type system, while neat, doesn't match anything under the JobsDB and JobStreet brands, or the direction chosen by the SEEK Asia design team.

MIGRATION GUIDE:

Before:

```jsx
<Text hero>Living Style Guides are the Best</Text>
```

After:

```js
<Text screaming>Living Style Guides are the Best</Text>
```

### CODE REVIEW

**Comment by mengtzu** [comment]
This isn't ready for merge, just creating the PR for ease of review

We'll need to chat with the SEEK Asia design team to validate the (many) assumptions associated with the type system

**Comment by mengtzu** [comment]
http://seek-asia-style-guide--43d1098f579a0ec5fff38df35de683bd96520111.surge.sh/text

(the docs site will need some work in general if we merge this, the sizes are a bit out of whack)

**Comment by mengtzu** [comment]
I won't have time to merge this as I'm off on holiday 🗾  - it would be valuable for someone to sit down with a designer and exercise this, get the 4px grid spacings right etc (and in particular implementing them in the JobCard via the variables)

**Comment by nicolassenechal** [comment]
Please correct me if I am wrong, but this is a breaking change from the Seek Styleguide and we won't be able to stay in sync after this. Is that correct?

**Comment by ZhenYongSeekAsia** [comment]
Im not sure about that, but i believe we will need more effort to sync if the new changes involve typography.

**Comment by nicolassenechal** [comment]
Jye Nicolson [10:35 PM] 
It will increase friction yes, but shouldn't make it impossible
[10:36] 
The style guide isn't useful without correct spaco and type anyway so short of a 6px/4px deathmatch between Cam and Joanna there's no helping it

**Comment by MingHo138** [comment]
I walk through Joanne (VD) and Patrick (FE) about these changes.
- We agree to align the style guide typography naming with SEEK Asia brand portal.
- We agree to move ahead with a 4px grid, and we document using 4 as a basic multiplier for white space in our brand portal white space guide: http://brand.seekasia.com/product/whitespace/

Shall we try implementing the 4px grid to JobAd card for a quick review?

**Comment by nicolassenechal** [comment]
Let's do this please :)

**Comment by ZhenYongSeekAsia** [comment]
@nicolassenechal @MingHo138 i think we should merge this branch and create another branch to experiment/adjust the grid on JobCard.

**Comment by manthachan** [comment]
yes, i think we should merge this branch first.
I have show the new grid job card layout to Ming & VD in HK, and committed the code.

**Pull request merged**
