### PR TITLE
Feature/update typography

### PR DESCRIPTION
**Pull request by patrickliu-sa**
Typography spec confirmed, which follow the rules below:

BREAKING CHANGE:
-

### Title type

Default font weight: 700 (equivalent to `bold`)
Other font weight options: 600 (equivalent to `semi-bold`)
Line height: corresponding `font-size` + 8 pixels (i.e. `@grid-base * 2`)

### Paragraph / plain text

Default font weight: 400 (equivalent to `normal`)
Other font weight options: 600, 700 (equivalent to `semi-bold` and `bold` respectively)
Line height: corresponding `font-size` + 4 pixels (i.e. `@grid-base`)

DEMO PAGE CHANGE:
-

### Old layout
old-typography

### New layout
new-typography

### CODE REVIEW

**Comment by patrickliu-sa** [comment]
Font weight `light` is not going to use in SEEK Asia style guide for now, therefore I've just took that out

**Comment by mengtzu** [comment]
This seems like it can generate off-grid line heights (I saw a 42px) - is that a good idea?

**Comment by patrickliu-sa** [comment]
Consider header should snap to the top of grid  as the very first item in a content block, I think it's ok.

Grid system should be all about precision of block components placement to grid layout, but title and paragraph should get more grace for their vertical height.

**Comment by mengtzu** [comment]
Not sure that makes sense.  There's nothing enforcing the grid other than the combined sizes and spacings of all the elements, if one of them is off grid everything else after them will be off grid too?

**Comment by patrickliu-sa** [comment]
In general text should be inline (not even inline-block).  It should have more freedom to use within a block-based component.

For the same reason, we can't enforce hirer write job ad with the "design" that respecting our `grid-base` system. 😸

**Comment by mengtzu** [comment]
The line height is what defines the height of the `Text` component, which is a block component.  If you wanted to have non-grid line heights, you'd have to do something else to guarantee they were always contained by on-grid block components; currently we don't have a mechanism for that.

**Comment by patrickliu-sa** [comment]
Prepared few mixins that respect DRY and better snap line-height to `@grid-base` so we can proceed with this PR first.

**Pull request merged**
