### PR TITLE
fix(Text): remove unnecessary error message

### PR DESCRIPTION
**Pull request by AlaaHamidah**
** Please provide as much detail as possible, but feel free to remove irrelevant sections **

it's causing an unnecessary error message showed for user in both Chrome & Firefox
image

BREAKING CHANGE:

no breaking

Please refer to Trello card : 
https://trello.com/c/yGUzjE4X

### CODE REVIEW

**Comment by mengtzu** [comment]
I think it would be a better idea to not nest the Text components?  The error is there for a reason.

**Comment by AlaaHamidah** [comment]
@mengtzu I would prefer too.. but what I figure out that the "nested" is coming from the Job Description which is an HTML coming from hirer side ..
on the other hand I don't find it useful to show this error to the user .. maybe in another way we can log this?

**Comment by mengtzu** [comment]
😕 how did a Text element get inside user generated content?

The idea behind this thing is the user would never see it, since the only people who can nest a `<Text>` are devs.  It shouldn't be possible for ugc to have the hashed class name once, let alone twice.

Agree this is very odd - could we comment it out for now, investigate and then put it back?  Did you actually see this error in prod?

**Comment by mengtzu** [comment]
OK yeah it's in prod.  I think we must be naively replacing things with `<Text />` somewhere 🤔

**Comment by AlaaHamidah** [comment]
> 😕 how did a Text element get inside user generated content?

@mengtzu  I really don't know exactly.. I'm also not able to simulate it on my local for some reason ! .. I just try to figure out what is happening on prod..
anyway I would comment this until we can find the correct cause & solution

**Pull request merged**
