### PR TITLE
fix(JobCard): move to external component

### PR DESCRIPTION
**Pull request by youwei91**
** Please provide as much detail as possible, but feel free to remove irrelevant sections **

{{ Reason for change }}

BREAKING CHANGE:

{{ Description of breaking API change }}

RFC URL:

{{ URL of associated RFC for API change }}

MIGRATION GUIDE:

Before:

```js
{{ Old code }}
```

After:

```js
{{ New code }}
```

EXAMPLE USAGE:

```js
{{ Code }}
```

### CODE REVIEW

**Comment by kosanna** [comment]
maybe just merge it directly into #401?

**Comment by kosanna** [comment]
I'm happy with the change, as usual it starts feeling itchy when you see something you want to refactor, but you know it has not been introduced in this PR 😂

**Comment by mengtzu** [comment]
I think editing the PR message to give some context would help you get that second approval 😓   What are we reviewing here? 😀

**Comment by youwei91** [comment]
@mengtzu mainly just move out some JobCard's inner component to external component for better viewing, after discuss with @kosanna decided to merge this PR to #401 , will close it

**Pull request closed without merging**
