### PR TITLE
Feature/brand headers

### PR DESCRIPTION
**Pull request by mengtzu**
The actual header is hacky and awful because I just stole CPP's code and did the bare minimum to make it work.  However it sets the pattern and makes it available to `srp-react` for demo purposes.

### CODE REVIEW

**Comment by derekchan-seekasia** [comment]
It is use for demo only? or we will go for this pattern in future?

**Comment by mengtzu** [comment]
@derekchan-seekasia we will definitely have the pattern of each brand exporting its own header like this.  I think the JobStreet one probably only needs a bit of refactoring and its brand-specific variables pulled into css-in-js.  There was nothing wrong with the CPP version, I just pulled it out of its multi-tenant build complex and had to patch it up accordingly.

**Comment by nicolassenechal** [comment]
Should we just leave this on a branch until we clean it?

**Comment by mengtzu** [comment]
We can, sure.  We can just push any changes we need for the demo to this branch, refactor/cherry pick it later

**Comment by mengtzu** [comment]
As mentioned in slack I'd like to merge this as-is, or bring it up to some kind of acceptable minimum level and then merge.  I'd like to have the style guide serving *something* for header and footer components, and it should be easier to iteratively amend these JobStreet components than start from scratch.

Can I get an approval to go ahead as-is or suggestions on how to amend it to be minimally acceptable?

**Pull request merged**
