### PR TITLE
style(Button): Remove generic CTA button style

### PR DESCRIPTION
**Pull request by patrickliu-sa**
**Call to action button** should always tie to a tenant, therefore, remove the generic CTA style to prevent confusion and misuse of CTA without the tenant being set.

Ref: https://github.com/seekinternational/seek-asia-style-guide/issues/342

### CODE REVIEW

**Comment by patrickliu-sa** [comment]
It's related to https://github.com/seekinternational/seek-asia-style-guide/issues/342

**Comment by ChanJit** [comment]
question, should we add something like

`[styles.root_callToAction]: color === 'callToAction' && (isJobStreet || isJobsDB)`

https://github.com/seekinternational/seek-asia-style-guide/blob/master/react/Button/Button.js#L56

**Comment by cm-seekasia** [comment]
Can remove isJobsDB and isJobStreet props? Use `context` instead?

**Comment by patrickliu-sa** [comment]
> question, should we add something like
> 
> `[styles.root_callToAction]: color === 'callToAction' && (isJobStreet || isJobsDB)`
> 
> https://github.com/seekinternational/seek-asia-style-guide/blob/master/react/Button/Button.js#L56

We'll use `StyleGuideContext` instead. (Thanks @cm-seekasia help me out on that)

**Pull request merged**
